language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t raneeshgomez/react-tests -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true raneeshgomez/react-tests npm run test

after_success:
  - docker build -t $DOCKER_ID/multi-client ./client
  - docker build -t $DOCKER_ID/multi-server ./server
  - docker build -t $DOCKER_ID/multi-worker ./worker
  - docker build -t $DOCKER_ID/multi-nginx ./nginx
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to Docker Hub
  - docker push $DOCKER_ID/multi-client
  - docker push $DOCKER_ID/multi-server
  - docker push $DOCKER_ID/multi-worker
  - docker push $DOCKER_ID/multi-nginx